volumes:
  mysql-data:

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: backend_php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    container_name: backend_nginx
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mysql:8.0
    container_name: backend_db
    volumes:
      - mysql-data:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3309:3306"
